name: Build and Release APK
on: push
jobs:
  hosting:
    name: Deploy Website
    runs-on: ubuntu-latest
    steps:
      # Checkout Repository
      - uses: actions/checkout@v3

      # Install Flutter command
      - name: Flutter action
        uses: subosito/flutter-action@v2.8.0
        with:
          channel: 'stable'

      # Build Website
      - name: Build Website
        run: |
          flutter config --enable-web
          flutter pub get
          flutter build web --release
        working-directory: ./

      # Deploy Firebase Hosting
      - name: Deploy Firebase Hosting
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:confo-card-79a5b
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_CONFO_CARD }}
          PROJECT_PATH: ./